### ISSUE TITLE
No output from EEGLogger C# example

### ISSUE THREAD

**Issue by chetanvijayin** [Emotiv/cortex-example#29] opened 2018-07-19 05:08 UTC
Hi all, Need help. I am able to run the EEGLOGGER code successfully but no data is being stored inside "EEGLoggerOutput.csv". The file is being created but no data is stored. Thanks

**Comment by nguoithichkhampha** [comment] 2018-07-19 06:41
Hi @chetanvijayin , which example you are working on ? C#, C++ ???
Do you have license to get eeg data ?

**Comment by chetanvijayin** [comment] 2018-07-19 06:42
Hi @nguoithichkhampha. I am working on C#. Yes I have got the Licence key.

**Comment by patdotme** [comment] 2018-07-20 08:42
Hi @chetanvijayin did you follow the README and do this:

> To run this example, you need put your EmotivID and license in Program.cs.

You will need to register an App ID via the Emotiv website in your Account page -> Cortex App:
https://www.emotiv.com/my-account/cortex-apps/

**Comment by chetanvijayin** [comment] 2018-07-23 06:37
@patdotme Yes. I got the license key and app ID but still there is no output. Please help me.

**Comment by nguoithichkhampha** [comment] 2018-07-31 08:50
Duplicate of #32

**Closed** 2018-07-31 08:54 UTC
