### ISSUE TITLE
EEGLogger C# example

### ISSUE THREAD

**Issue by chetanvijayin** [Emotiv/cortex-example#30] opened 2018-07-20 00:19 UTC
Hello, I am trying to read some data using blue-tooth dongle. I am sure I am making some silly mistake and need your help to solve the issue. I am working on the example EEGLogger from Csharp folder to start with - which is given in the examples but I am unable to record data. To understand what is going wrong- I added some log statements in the code, and apparently, it never goes inside the write function. Does that mean it is not receiving the data (event is not taking place?)? some logs as attached and at the end after pressing enter I get msg as "unsubscribe session with stream xyz fail" and the window closes. EEG Logger file for data is empty ( size 0 kb) Could you please help me understand what is going wrong? Thanks

**Comment by chetanvijayin** [comment] 2018-07-20 00:26
The log statement is:

EEG LOGGER
Please wear Headset with good signal!!!
Websocket Client Connected
Querry Headset successfully
Headset Connected
Selected HeadsetID EPOCPLUS-3B9ACCE0
Querry Headset successfully
Selected HeadsetID EPOCPLUS-3B9ACCE0
Username :****
inside p.AccessCtr.IsLogin
Authorize successfully!!!. Access Token ****
Querry Headset successfully
Selected HeadsetID EPOCPLUS-3B9ACCE0
Querry Profile Successfully
inside if (!p.IsCreateSession)
Create SESSION successfully
inside if (p.IsCreateSession)
Querry Headset successfully
Selected HeadsetID EPOCPLUS-3B9ACCE0
Press Enter to exit
Querry Headset successfully
Selected HeadsetID EPOCPLUS-3B9ACCE0
Querry Headset successfully
Selected HeadsetID EPOCPLUS-3B9ACCE0
Querry Headset successfully

**Comment by nguoithichkhampha** [comment] 2018-07-31 08:54
Duplicate of #29

**Closed** 2018-07-31 08:55 UTC
